language: cpp
script: make
sudo: no
dist: trusty
os:
- linux
addons:
  apt:
    packages:
    - python-ply
    - linux-headers-generic
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

