language: cpp
cache:
  directories:
  - Bluespec-2015.09.bata2
before_script:
- if [ -d Bluespec-2015.09.beta2 ] ; then echo bluespec cached; else curl http://www.bluespec.com/downloads/Bluespec-2015.09.beta2.tar.gz | tar -zxf - ; fi
- mkdir -p lib
- ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
env:
  global:
    - BLUESPECDIR=$PWD/Bluespec-2015.09.beta2/lib
    - PATH=$PATH:$PWD/Bluespec-2015.09.beta2/bin
    - LD_LIBRARY_PATH=$PWD/lib
    - secure: "JMM9GHMCVIJUxQh1wAepLUVjfdSbVB0dL5LGZN6FoKNTXiAZX8wLiGlb/HvtLJFv2YmL3BT7eqC0Hbp4juQ5Q3SmIdnJ0oX9xp6ODQ6PgfpTyl6vBsOnEVp6xtz39Ck/8tgZ28eToOaJfbbcit8ESPsiI4cq4R6Dqjq1a8HFLNY="
  matrix:
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/simple CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/strstr CONNECTAL_ARCH=bluesim
script:
- make scripts/syntax/parsetab.py; cd $CONNECTAL_TEST; make build.$CONNECTAL_ARCH run.$CONNECTAL_ARCH
sudo: no
dist: trusty
os:
- linux
addons:
  apt:
    sources:
    - sourceline: 'ppa:jamey-hicks/connectal'
    packages:
    - python-ply
    - libgmp10
    - verilator
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

