language: cpp
script: make scripts/syntax/parsetab.py
sudo: no
dist: trusty
os:
- linux
addons:
  apt:
    packages:
    - python-ply
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

