language: cpp
cache:
  directories:
before_script:
- if [ -d Bluespec-2015.09.beta2 ] ; then echo bluespec cached; else curl http://www.bluespec.com/downloads/Bluespec-2015.09.beta2.tar.gz | tar -zxf - ; fi
- mkdir -p lib
- ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
env:
  global:
    - BLUESPECDIR=$PWD/Bluespec-2015.09.beta2/lib
    - PATH=$PATH:$PWD/Bluespec-2015.09.beta2/bin
    - LD_LIBRARY_PATH=$PWD/lib
  matrix:
    - CONNECTAL_TEST=examples/echo CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/echopy CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/simple CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=bluesim
    - CONNECTAL_TEST=examples/memcpy CONNECTAL_ARCH=verilator
    - CONNECTAL_TEST=examples/strstr CONNECTAL_ARCH=bluesim
script:
- ls Bluespec-2015.09.beta2
- export PYTHONPATH=$PWD/scripts; make scripts/syntax/parsetab.py; cd $CONNECTAL_TEST; make build.$CONNECTAL_ARCH run.$CONNECTAL_ARCH
sudo: no
dist: trusty
os:
- linux
addons:
  apt:
    sources:
    - sourceline: 'ppa:jamey-hicks/connectal'
    packages:
    - python-dev
    - python-ply
    - libgmp10
    - libjsoncpp-dev
    - verilator
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

